---
title: "Spectra test"
author: "Lucy Grigoroff"
date: "2023-07-04"
output: html_document
---
#FUNCTIONS
```{r}
functionDir <- "./R/"
functionList <- list.files(path = functionDir)
for(i in functionList){
  source(paste0(functionDir,i))
}

post_processing <- function(X, ppm, type = FALSE, bc = FALSE, pqn = FALSE) {
  if (type == TRUE) {
    X=calibrate(X,ppm, type='glucose')
  }  
  ##    Remove water peak from the reduced spectra data X_reduced (4.6 to 4.85)
  idx = get_idx(range = c(4.6,4.85),ppm) # change this part to 4.6 to 6.0 to remove both water and urea
  Xc1 = X[,-idx]
  ppm1 = ppm[-idx]
  
  ##    Remove TPS and lower ppm range
  idx = get_idx(range = c(min(ppm),0.4),ppm1)
  Xc2 = Xc1[,-idx]
  ppm2 = ppm1[-idx]
  
  ##    Remove higher ppm range with no signal
  idx = get_idx(range = c(9.5,max(ppm)),ppm2)
  Xc3 = Xc2[,-idx]
  ppm3 = ppm2[-idx]
  
  ##    Baseline correction
  if (bc == TRUE) {
    Xc3 = bcor(Xc3)
  }
  ##    Normalisation (scaling)
  if(pqn == TRUE){
    Xc3 = pqn(Xc3, add_DilF = 'dquott', bin=NULL)
  }
  
  return(list("Xn" = Xc3, "ppm" = ppm3))
} 

plsc=function (obj, pc, an, title = "", qc, legend = "in", cv = TRUE, sh,
               ...) 
{
  if (missing(pc)) {
    if (grepl("PCA", class(obj)[1])) {
      pc = c(1, 2)
    }
    if (grepl("OPLS", class(obj)[1])) {
      pc = c("1", "o1")
    }
  }
  if (cv == TRUE & grepl("OPLS", class(obj)[1])) {
    etype = "t_cv"
  }
  else {
    etype = "t"
  }
  res = metabom8:::.viz_df_helper(obj, pc, an, type = etype)
  sc = res$df
  type = "categorical"
  if (ncol(sc) > 2 && is.numeric(sc[, 3])) {
    type = "continuous"
  }
  if (is.null(res$an_le) || is.na(res$an_le)) {
    stop("Check helper function .viz_df_helper")
  }
  df =  metabom8:::.hotellingsT2(x = sc[, 1], y = sc[, 2])
  g <- ggplot() + geom_polygon(data = df, aes_string(x = "V1", 
                                                     y = "V2"), fill = NA, alpha = 0.4, colour = "black", 
                               linetype = 3) + geom_hline(yintercept = 0, colour = "gray70") + 
    geom_vline(xintercept = 0, colour = "gray70") + theme_bw() + 
    labs(caption = expression("Dashed line: Hotelling's T"^2 ~ 
                                "ellipse (" * alpha * "=0.95)"))
  if (res$an_le == 1) {
    switch(type, categorical = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3]), alpha = 0.7, 
                          shape = 16, size=sh)
    }, continuous = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3]), alpha = 1, 
                          shape=16, size=sh) + scale_colour_gradientn(colours = matlab.like2(10), 
                                                                      breaks = breaks_pretty(), ...)
    })
    g <- g + labs(title = title, colour = colnames(sc)[3])
  }
  if (res$an_le == 2) {
    switch(type, categorical = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3], shape = colnames(sc)[4]), 
                          alpha = 1, size=sh)
    }, continuous = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3], shape = colnames(sc)[4]), 
                          alpha = 1, size=sh) + scale_colour_gradientn(colours = matlab.like2(10), 
                                                              breaks = breaks_pretty(), ...)
    })
    g <- g + labs(title = title, colour = colnames(sc)[3], 
                  shape = colnames(sc)[4])
  }
  if (res$an_le == 3) {
    switch(type, categorical = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3], shape = colnames(sc)[4]), 
                          alpha = 1, size = sh) + geom_text_repel(data = sc, aes_string(colnames(sc)[1], 
                                                                             colnames(sc)[2], label = colnames(sc)[5]))
    }, continuous = {
      g <- g + geom_point(data = sc, aes_string(colnames(sc)[1], 
                                                colnames(sc)[2], colour = colnames(sc)[3], shape = colnames(sc)[4]), 
                          alpha = 1, size = sh) + scale_colour_gradientn(colours = matlab.like2(10), 
                                                              breaks = breaks_pretty(), ...) + geom_text_repel(data = sc, 
                                                                                                               aes_string(colnames(sc)[1], colnames(sc)[2], 
                                                                                                                          label = colnames(sc)[5]))
    })
    g <- g + labs(title = title, colour = colnames(sc)[3], 
                  shape = colnames(sc)[4], label = colnames(sc)[5])
  }
  if (!missing(qc) && all(!is.na(qc)) && is.numeric(qc)) {
    df_qc <- data.frame(x = sc[qc, 1], y = sc[qc, 2])
    g <- g + geom_point(data = df_qc, aes_string("x", "y"), 
                        alpha = 0.7, colour = "black")
  }
  switch(class(obj)[1], PCA_MetaboMate = {
    g <- g + scale_x_continuous(name = paste("PC ", pc[1], 
                                             " (", round(obj@R2[pc[1]] * 100, 1), " %)", sep = "")) + 
      scale_y_continuous(name = paste("PC ", pc[2], " (", 
                                      round(obj@R2[pc[2]] * 100, 1), " %)", sep = ""))
  }, OPLS_MetaboMate = {
    if (ncol(obj@t_orth) > 1) {
      comp <- "orthogonal components"
    } else {
      comp <- "orthogonal component"
    }
    if (etype != "t_cv") {
      if (grepl("DA", obj@type)) {
        g <- g + scale_x_continuous(name = expression(t[pred])) + 
          scale_y_continuous(name = expression(t[orth])) + 
          ggtitle(paste("OPLS-DA: 1+", obj@nPC, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC], 
                                                 2), ", R2Y=", round(obj@summary$R2Y[obj@nPC], 
                                                                     2), ", Q2=", round(obj@summary$Q2[obj@nPC], 
                                                                                        2), ", CV-AUROC=", round(obj@summary$AUROC[obj@nPC], 
                                                                                                                 2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      } else {
        g <- g + scale_x_continuous(name = expression(t[pred])) + 
          scale_y_continuous(name = expression(t[orth])) + 
          ggtitle(paste("OPLS-R: 1+ ", obj@nPC, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC], 
                                                 2), ", R2Y=", round(obj@summary$R2Y[obj@nPC], 
                                                                     2), ", Q2=", round(obj@summary$Q2[obj@nPC], 
                                                                                        2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      }
    } else {
      if (grepl("DA", obj@type)) {
        g <- g + scale_x_continuous(name = expression(t[pred][","][cv])) + 
          scale_y_continuous(name = expression(t[orth][","][cv])) + 
          ggtitle(paste("OPLS-DA: 1+", obj@nPC, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC], 
                                                 2), ", R2Y=", round(obj@summary$R2Y[obj@nPC], 
                                                                     2), ", Q2=", round(obj@summary$Q2[obj@nPC], 
                                                                                        2), ", AUROC=", round(obj@summary$AUROC[obj@nPC], 
                                                                                                              2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      } else {
        g <- g + scale_x_continuous(name = expression(t[pred][","][cv])) + 
          scale_y_continuous(name = expression(t[orth][","][cv])) + 
          ggtitle(paste("OPLS-R: 1+", obj@nPC, " ", "comp.", 
                        " (R2X=", round(obj@summary$R2X[obj@nPC], 
                                        2), ", R2Y=", round(obj@summary$R2Y[obj@nPC], 
                                                            2), ", Q2=", round(obj@summary$Q2[obj@nPC], 
                                                                               2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      }
    }
  }, OPLS_metabom8 = {
    if (ncol(obj@t_orth) > 1) {
      comp <- "orthogonal components"
    } else {
      comp <- "orthogonal component"
    }
    if (etype != "t_cv") {
      if (grepl("DA", obj@type)) {
        g <- g + scale_x_continuous(name = expression(t["pred"])) + 
          scale_y_continuous(name = expression(t["orth"])) + 
          ggtitle(paste("OPLS-DA: 1+", obj@nPC - 1, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC - 
                                                                   1], 2), ", AUROC=", round(obj@summary$AUROC[obj@nPC - 
                                                                                                                 1], 2), ", CV-AUROC=", round(obj@summary$AUROC_CV[obj@nPC - 
                                                                                                                                                                     1], 2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      } else {
        g <- g + scale_x_continuous(name = expression(t[pred])) + 
          scale_y_continuous(name = expression(t[orth])) + 
          ggtitle(paste("OPLS-R: 1+", obj@nPC - 1, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC - 
                                                                   1], 2), ", R2Y=", round(obj@summary$R2Y[obj@nPC - 
                                                                                                             1], 2), ", Q2=", round(obj@summary$Q2[obj@nPC - 
                                                                                                                                                     1], 2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      }
    } else {
      if (grepl("DA", obj@type)) {
        g <- g + scale_x_continuous(name = expression(t[pred][","][cv])) + 
          scale_y_continuous(name = expression(t[orth][","][cv])) + 
          ggtitle(paste("OPLS-DA: 1+", obj@nPC - 1, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC - 
                                                                   1], 2), ", AUROC=", round(obj@summary$AUROC[obj@nPC - 
                                                                                                                 1], 2), ", CV-AUROC=", round(obj@summary$AUROC_CV[obj@nPC - 
                                                                                                                                                                     1], 2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      } else {
        g <- g + scale_x_continuous(name = expression(t[pred][","][cv])) + 
          scale_y_continuous(name = expression(t[orth][","][cv])) + 
          ggtitle(paste("OPLS-R:1 + ", obj@nPC - 1, " ", 
                        "comp.", " (R2X=", round(obj@summary$R2X[obj@nPC - 
                                                                   1], 2), ", R2Y=", round(obj@summary$R2Y[obj@nPC - 
                                                                                                             1], 2), ", Q2=", round(obj@summary$Q2[obj@nPC - 
                                                                                                                                                     1], 2), ")", sep = "")) + theme(plot.title = element_text(size = 10))
      }
    }
  }, PCA_metabom8 = {
    g <- g + scale_x_continuous(name = paste("PC ", pc[1], 
                                             " (", round(obj@Parameters$R2[pc[1]] * 100, 1), " %)", 
                                             sep = "")) + scale_y_continuous(name = paste("PC ", 
                                                                                          pc[2], " (", round(obj@Parameters$R2[pc[2]] * 100, 
                                                                                                             1), " %)", sep = ""))
  })
  if (legend == "in") {
    g <- g + theme(legend.position = c(1.01, 1.02), legend.justification = c(1, 
                                                                             1))
  }
  return(g)
}

```
#ANNOTATION
Take old annotation.dae and update it.
```{r}
#old annotation.dae
ANNO<-local(get(load("~/OneDrive - Murdoch University/datasets/covid19/mauritius/DataElements/covid19_mauritius_ANNO.daE")))
ANNO<-ANNO@obsDescr[[1]]

#Keep only essential info
ANNO <- ANNO[,1:7]
class(ANNO$sourceID) #character
ANNO$sourceID <- as.integer(ANNO$sourceID)

#Replace old info with new 
updated060623 <- read.csv("~/Documents/Mauritius/Deidentified_Metabolic_data_updated_06_06_23.csv")
class(updated060623$Survey.No.)
colnames(updated060623)[which(names(updated060623) == "Survey.No.")] <- "sourceID"

ANNO <- right_join(ANNO, updated060623, by = "sourceID")

#split into ser and pla
SER_ANNO<-ANNO[which(ANNO$sampleMatrixType=="SER"),]
PLA_ANNO<-ANNO[which(ANNO$sampleMatrixType=="PLA"),]

rm(updated060623)
```

```{r}
#SER NMR NOESY
noesy<-local(get(load("~/Documents/LucyDatasets/covid19_mauritius_SER_COVr22_PROF.PLASMA.NOESY.daE")))

SER_NOESY_data<-noesy@.Data
ppm<-as.numeric(noesy@varName)

SER_NOESY_meta1<-noesy@obsDescr[[1]]
SER_NOESY_meta1$sourceID<-sapply(strsplit(SER_NOESY_meta1$UUID,"_"),"[",2)
SER_NOESY_info<-noesy@obsDescr[[5]] 
#SER_NOESY_meta1<-merge(SER_NOESY_meta1,SER_NOESY_info, by = "path")
rm(SER_NOESY_info,noesy)



```
##removals and matches
```{r}
#post processing
res<-post_processing(SER_NOESY_data,ppm,type = TRUE, bc = TRUE, pqn = FALSE )
SER_NOESY_data<-res[[1]]
ppm<-res[[2]]
colnames(SER_NOESY_data)<-ppm

#remove LTRs
SER_NOESY_data<-SER_NOESY_data[grep("COV",SER_NOESY_meta1$sampleID),]
SER_NOESY_meta1<-SER_NOESY_meta1[grep("COV",SER_NOESY_meta1$sampleID),]

#change to data to df and attach sampleIDs
SER_NOESY_data <-as.data.frame(SER_NOESY_data)
SER_NOESY_data$sampleID <- SER_NOESY_meta1$sampleID

#deal with reruns
remove_id<-gsub(".1","",SER_NOESY_meta1$sampleID[grep(".",SER_NOESY_meta1$sampleID,fixed = TRUE)],fixed = TRUE)
SER_NOESY_data<-SER_NOESY_data[-which(SER_NOESY_meta1$sampleID %in% remove_id),]
SER_NOESY_meta1<-SER_NOESY_meta1[-which(SER_NOESY_meta1$sampleID %in% remove_id),]
SER_NOESY_meta1$sampleID<-gsub(".1","",SER_NOESY_meta1$sampleID,fixed = TRUE)
SER_NOESY_data$sampleID<-gsub(".1","",SER_NOESY_data$sampleID,fixed = TRUE)

#remove sample 299
SER_NOESY_data<-SER_NOESY_data[-which(SER_NOESY_meta1$sourceID=="299"),]
SER_NOESY_meta1<-SER_NOESY_meta1[-which(SER_NOESY_meta1$sourceID=="299"),]

```

##Matching
```{r}
#match serum anno with noesy annotation with sampleID
SER_NOESY_meta2 <- SER_ANNO[match(SER_NOESY_meta1$sampleID, SER_ANNO$sampleID),]

#merge all noesy anno
SER_NOESY_meta1$sourceID <-as.integer(SER_NOESY_meta1$sourceID)
SER_NOESY_meta <- merge(SER_NOESY_meta1, SER_NOESY_meta2, by=c("sampleID", "sourceID", "projectName", "cohortName", "sampleMatrixType"))

rm(SER_NOESY_meta1, SER_NOESY_meta2)
```


## tests

```{r pressure}


mod<-PCA(data = SER_NOESY_data[,-38623], rank = 2)

idx<- is.na(SER_NOESY_meta$Have.you.ever.been.tested.positive.to.COVID.19..)
SER_NOESY_meta[idx,106] <- 2
mod2 <- oplsda(X = SER_NOESY_data[,-38623], Y = as.factor(SER_NOESY_meta[,106]), type = "PLS")
mod3 <- oplsda(X = SER_NOESY_data[,-38623], Y = as.factor(SER_NOESY_meta[,106]), type = "OPLS")

PlotLoadSpec(model=mod2, roi = c(0.5, 6))

model = mod2 
PC = 1 
type = "Backscaled"
roi = c(6,9.5)


    method<-model@typeC
    res<-model@summaryDF
  
      df<-data.frame(-model@loadingMN)
      x<-as.numeric(rownames(df))
      idx<-which(x>roi[1] & x<roi[2])
      cen<--data.frame(model@xSdVn[idx])
      df<-df[idx,PC]
      x<-x[idx]
      m<-abs(df)
      y<-df*cen
      names(y)[1]<-"y"
      col<-(m - min(m))/(max(m) - min(m))
      df<-data.frame(x = x,y = y,col = col)
      raCol = NULL

   ggplot(df,aes(x = x, y = y,color = col))+geom_line()+
      scale_x_reverse(breaks = scales::breaks_pretty(n = 15))+
      scale_colour_gradientn(colors = colorRamps::matlab.like2(10),
                             limits = raCol,
                             name = expression("|p"["sc"] * "|")) +
      labs(title = method,
           subtitle = type,
           caption = paste0("component: ", PC, " loadings"),
           x = expression(delta ~ {}^1 * H ~ (ppm)),
           y = "") +
      theme_bw()
  
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
